### ISSUE TITLE
error: alsaplusplus/pcm.tpp: No such file or directory 

### ISSUE THREAD

**Issue by mehranmd** [maximus5684/alsaplusplus#4]
Hello sir,
Thnx for sharing in advance.
I built your library with these steps:
`mkdir build`
`cd build`
`cmake ..`
`make`
`sudo make install`
output :
`[100%] Built target AlsaPlusPlus
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/libAlsaPlusPlus.so.0.1.1
-- Up-to-date: /usr/local/lib/libAlsaPlusPlus.so.0
-- Up-to-date: /usr/local/lib/libAlsaPlusPlus.so
-- Up-to-date: /usr/local/include/alsaplusplus/common.hpp
-- Up-to-date: /usr/local/include/alsaplusplus/error.hpp
-- Up-to-date: /usr/local/include/alsaplusplus/mixer.hpp
-- Up-to-date: /usr/local/include/alsaplusplus/pcm.hpp
`
then i created a simple console application with qt creator and added your wrapper to the .pro file.
`LIBS+= -lasound`
`LIBS+= -lalsaplusplus`
on building the example project i face the error which point me to a file which is not there.
`/usr/local/include/alsaplusplus/pcm.hpp:63:12: fatal error: alsaplusplus/pcm.tpp: No such file or directory
   #include <alsaplusplus/pcm.tpp>`

any idea what is wrong.
I use elementary os 5.

**Comment by mehranmd** [comment]
so basically this file (pcm.tpp) is not present in the 
`/usr/local/include/alsaplusplus`

**Comment by maximus5684** [comment]
Thanks for letting me know about the bug! Would you mind testing the branch `fix/missing-install-file` and commenting on #5 once you've tested it?

**Comment by mehranmd** [comment]
Sure thing.
